# Dependencies
markdown:         kramdown
kramdown:
  math_engine: mathjax
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Andrew James Olson
tagline:          ''
description:      'documenting projects and whatnot'
url:              http://andrewjamesolson.com
baseurl:          /

author:
  name:           'Andrew Olson'
  github:         https://github.com/andrewinadoghat 

paginate:         5

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate

 
